/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctrineRouteImport } from './routes/doctrine'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ApiForgeRouteImport } from './routes/api/forge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctrineRoute = DoctrineRouteImport.update({
  id: '/doctrine',
  path: '/doctrine',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForgeRoute = ApiForgeRouteImport.update({
  id: '/api/forge',
  path: '/api/forge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctrine': typeof DoctrineRoute
  '/vault': typeof VaultRoute
  '/api/forge': typeof ApiForgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctrine': typeof DoctrineRoute
  '/vault': typeof VaultRoute
  '/api/forge': typeof ApiForgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctrine': typeof DoctrineRoute
  '/vault': typeof VaultRoute
  '/api/forge': typeof ApiForgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/doctrine' | '/vault' | '/api/forge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doctrine' | '/vault' | '/api/forge'
  id: '__root__' | '/' | '/doctrine' | '/vault' | '/api/forge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctrineRoute: typeof DoctrineRoute
  VaultRoute: typeof VaultRoute
  ApiForgeRoute: typeof ApiForgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctrine': {
      id: '/doctrine'
      path: '/doctrine'
      fullPath: '/doctrine'
      preLoaderRoute: typeof DoctrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forge': {
      id: '/api/forge'
      path: '/api/forge'
      fullPath: '/api/forge'
      preLoaderRoute: typeof ApiForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctrineRoute: DoctrineRoute,
  VaultRoute: VaultRoute,
  ApiForgeRoute: ApiForgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
